name: Linux CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      SQLServer:
        image: mcr.microsoft.com/mssql/server:2017-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: sqlServerPassw0rd
        ports:
          - 1433:1433

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libssl-dev libkrb5-dev libgnutls28-dev
        sudo apt-get install autoconf automake libtool
        sudo apt-get install gperf gettext

    - name: configure
      run: |
        autoreconf -i
        ./configure --with-gnutls  --enable-silent-rules --prefix=/tmp/freetds

    - name: make
      run: make

    - name: install
      run: |
        make install
        (cd ./samples; ./unixodbc.install.sh)

    - name: make check
      env:
        TDSPWDUID: sa
        TDSPWDPWD: sqlServerPassw0rd
        TDSPWDSRV: localhost
        TDSPWDDB: tempdb
      run: |
        ./misc/write_PWD_from_env_vars.sh
        (cd ./samples; ./unixodbc.install.sh)
        make check VERBOSE=1

    - name: make distcheck
      run: make distcheck
